### ISSUE TITLE
Make it responsive for tablets and mobiles

### ISSUE THREAD

**Issue by jebarjonet** [jebarjonet/jemennuiev2#2]
Often used on smartphones, responsivity is a feature. Should use responsive mixins in https://github.com/jebarjonet/jemennuiev2/blob/master/client/common/mixins.less

```less
@import '../common/mixins';

:local {
  color: red;

  @media @tablets, @mobiles {
    color: blue;
  }

  @media @tablets {
    margin-top: 10px;
  }
}
```
